kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jmeter-shared-disk-sc
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS