name: $(BuildID)
trigger: none

jobs:
  - job: Create_Resources
    displayName: Create_Resources
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 20
    steps:
      - task: AzureCLI@2
        displayName: Create cluster dynamically with ARM
        inputs:
          azureSubscription: mygroup
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            output=$(az deployment group create --name temp$(Build.BuildID) --resource-group $(rgroup) --template-file $(System.DefaultWorkingDirectory)/pipelines/azure/arm/k8.json --parameters nodeSize=Standard_D2_v2 nodeCount=2 clusterNamePrefix=perf)
            cname=$(echo $output |jq -r '.properties.outputs.name.value')
            echo "Cluster name created: $cname"
            echo "##vso[task.setvariable variable=cname]${cname}"

      - task: AzureCLI@2
        displayName: Create a service connection to cluster
        inputs:
          azureSubscription: mygroup
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            bash $(System.DefaultWorkingDirectory)/pipelines/azure/arm/delete_service_connection.sh gstarczewski jmeter gstarczewski $(pat) $(name)
            bash $(System.DefaultWorkingDirectory)/pipelines/azure/arm/create_service_connection.sh gstarczewski jmeter gstarczewski $(pat) $(name) $(cname) $(rgroup) $(System.DefaultWorkingDirectory)/pipelines/azure/arm

      - task: AzureCLI@2
        displayName: Create cluster from ARM
        inputs:
          azureSubscription: mygroup
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az aks delete --name $(cname) --resource-group $(rgroup) --yes --no-wait