name: $(BuildID)
trigger: none

jobs:
  - job: Create_Resources
    displayName: Create_Resources
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 5
    steps:
      - task: AzureCLI@2
        displayName: Azure CLI
        inputs:
          azureSubscription: mygroup
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            bash $(System.DefaultWorkingDirectory)/pipelines/azure/arm/create_service_connection.sh gstarczewski jmeter gstarczewski $(pat) $(name) perf_qinlkwwubxksw mygroup $(System.DefaultWorkingDirectory)/pipelines/azure/arm