name: $(BuildID)
trigger: none

jobs:
  - job: Create_Resources
    displayName: Create_Resources
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 20
    variables:
      k8conn: k8_$(Build.BuildID)
    steps:
      - task: AzureCLI@2
        displayName: Create cluster dynamically with ARM
        inputs:
          azureSubscription: mygroup
          scriptType: bash
          scriptPath: $(System.DefaultWorkingDirectory)/pipelines/azure/arm/create_cluster_and_connection.sh
          arguments: temp$(Build.BuildID) $(rgroup) $(System.DefaultWorkingDirectory)/pipelines/azure/arm/k8.json Standard_D2_v2 2 perf_$(Build.BuildID)_ cname gstarczewski jmeter gstarczewski $(pat) $(k8conn) $(System.DefaultWorkingDirectory)/pipelines/azure/arm

      - task: AzureCLI@2
        displayName: Delete cluster and connection
        inputs:
          azureSubscription: mygroup
          scriptType: bash
          scriptPath: $(System.DefaultWorkingDirectory)/pipelines/azure/arm/delete_cluster_and_connection.sh
          arguments: $(System.DefaultWorkingDirectory)/pipelines/azure/arm $(cname) $(rgroup) gstarczewski jmeter gstarczewski $(pat) $(k8conn)

