name: $(BuildID)
trigger: none
variables:
  armModulePath: $(System.DefaultWorkingDirectory)/pipelines/azure/arm
  k8conn: k8_$(Build.BuildID)
  armServiceConnection: mygroup
  clusterNodeSize: Standard_D2_v2
  clusterNodeNumber: 2
  devOpsOrg: gstarczewski
  devOpsProject: jmeter
  devOpsPatUser: gstarczewski
  devOpsPat: $(pat)
jobs:
  - job: Create_Resources
    displayName: Create_Resources
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 20
    steps:
      - task: AzureCLI@2
        displayName: Create cluster/connection
        inputs:
          azureSubscription: $(armServiceConnection)
          scriptType: bash
          scriptPath: $(armModulePath)/create_cluster_and_connection.sh
          arguments: temp$(Build.BuildID) $(rgroup) $(armModulePath)/k8.json $(clusterNodeSize) $(clusterNodeNumber) perf_$(Build.BuildID)_ cname $(devOpsOrg) $(devOpsProject) $(devOpsPatUser) $(devOpsPat) $(k8conn) $(armModulePath)

      - task: AzureCLI@2
        displayName: Delete cluster/connection
        inputs:
          azureSubscription: $(armServiceConnection)
          scriptType: bash
          scriptPath: $(armModulePath)/delete_cluster_and_connection.sh
          arguments: $(armModulePath)/pipelines/azure/arm $(cname) $(rgroup) $(devOpsOrg) $(devOpsProject) $(devOpsPatUser) $(devOpsPat) $(k8conn)

