#Contains chart necessary to start a jmeter aks cluster with storage provisioned uniquely for each test run
apiVersion: v2
name: storage-cluster
description: Helm chart to test CRUX volume mounts
type: application
maintainers:
  - email: UK_KTI-DevOps@pwc.com
    name: KTI-DevOps Team
version: 0.8.0