parameters:
  - name: mode
    displayName: 'Which template to use ?'
    type: string
    default: jmeter

jobs:
  - template: run.jmeter.kubernetes.template.yaml
    parameters:
      mode: ${{ parameters.mode }}