parameters:
  - name: mode
    displayName: 'Which template to use ?'
    type: string
    default: jmeter

  - name: linux_pool
    type: string
    default: microsoft_hosted

  - name: crux_steps
    type: object
    default:  [
               'step.crux_clone.yaml',
               'step.tests_clone.yaml',
               'step.prepare_tests.yaml',
               'step.create_cluster.yaml',
               'step.configure_cluster.yaml',
               'step.deploy_to_cluster.yaml',
               'step.jmeter_tests.yaml',
               'step.workbooks_upload.yaml',
               'step.archive_jmeter_report.yaml',
               'step.archive_jmeter_results.yaml',
               'step.archive_jmeter_log.yaml',
               'step.archive_jmeter_errors.yaml',
               'step.archive_jmeter_server_logs.yaml',
               'step.junit.yaml',
               'step.junit_publish.yaml',
               'step.delete_cluster.yaml'
              ]
jobs:
  - job: JMeter_Tests
    ${{ if eq(parameters.linux_pool, 'microsoft_hosted') }}:
       pool:
         vmImage: 'ubuntu-latest'
    condition: not(eq(variables['jmeter_tests'], false))
    variables:
      - template: default.variables.yaml
        parameters:
          mode: ${{ parameters.mode }}

    displayName: JMeter pipeline - test
    steps:
    - ${{ if eq(parameters.mode, 'tests') }}:
      - template: insert_step.yaml
        parameters:
          source_folder: mocks
          step_list: ${{ parameters.crux_steps }}

    - ${{ if not(eq(parameters.mode, 'tests')) }}:
        - template: insert_step.yaml
          parameters:
            source_folder: steps
            step_list: ${{ parameters.crux_steps }}