parameters:
  - name: mode
    displayName: 'Which template to use ?'
    type: string
    default: jmeter

  - name: debug
    displayName: 'Display additional diagnostics ?'
    type: boolean
    default: false

jobs:
  - job: Debug
    condition: and(succeeded(), eq('${{ parameters.debug }}', true))
    displayName: Mode selection
    steps:
      - bash: |
            echo "Run mode selected:"  ${{ parameters.mode }}
            echo "Debug:"  ${{ parameters.debug }}
        displayName: Display selected mode

  - ${{ if eq(parameters.mode,'jmeter') }}:
    - template: run.jmeter.kubernetes.template.yaml
  - ${{ if eq(parameters.mode,'tests') }}:
    - template: run.jmeter.kubernetes.template.tests.yaml
    - template: run.jmeter.kubernetes.template.yaml
      parameters:
        mode: ${{ parameters.mode }}