parameters:
  - name: mode
    displayName: 'Which template to use ?'
    type: string
    default: jmeter

  - name: debug
    displayName: 'Display additional diagnostics ?'
    type: boolean
    default: false

variables:
  crux_clone: false
  prepare_test: false
  scale_slaves_down: false
  scale_slaves_up: false
  scale_master_up: false
  scale_master_down: false
  login_to_cluster: false
  jmeter_tests: false
  archive_jmeter_repor: false
  archive_results_file: false
  archive_log: false
  evaluate_as_junit_tests: false
  publish_junit_result: false


jobs:
  - job: Debug
    condition: and(succeeded(), eq('${{ parameters.debug }}', true))
    displayName: Mode selection
    steps:
      - bash: |
            echo "Run mode selected:"  ${{ parameters.mode }}
            echo "Debug:"  ${{ parameters.debug }}
        displayName: Display selected mode

  - ${{ if eq(parameters.mode,'jmeter') }}:
    - template: run.jmeter.kubernetes.template.yaml
  - ${{ if eq(parameters.mode,'tests') }}:
    - template: run.jmeter.kubernetes.template.tests.yaml
    - template: run.jmeter.kubernetes.template.dummy.yaml