parameters:
  - name: mode
    displayName: 'Which template to use ?'
    type: string
    default: jmeter

jobs:
  - job: Selection
    displayName: Selection
    steps:
      - bash: |
            echo "Mode selected:"  $(mode)
  - ${{ if not(eq(parameters.mode, 'tests')) }}:
      - template: run.jmeter.kubernetes.template.yaml
  - ${{ if eq(parameters.mode, 'tests') }}:
      - template: run.jmeter.kubernetes.template.tests.yaml