parameters:
  - name: mode
    displayName: 'Which template to use ?'
    type: string
    default: jmeter

jobs:
  - job: Debug
    displayName: Mode selection
    steps:
      - bash: |
            echo "Run mode selected:"  $(mode)
            echo "Parameter:"  ${{ parameters.mode }}
        displayName: Display selected mode

  - ${{ if contains(parameters.mode,'jmeter') }}:
    - template: run.jmeter.kubernetes.template.yaml
  - ${{ if contains(parameters.mode,'tests') }}:
    - template: run.jmeter.kubernetes.template.tests.yaml