jobs:
  - job: Test_the_Framework
    displayName: BATS tests
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 5
    steps:
      - checkout: crux
        displayName: CRUX clone

      - task: ShellScript@2
        displayName: Install BATS
        inputs:
          scriptPath: $(System.DefaultWorkingDirectory)/modules/bats/install.sh

      - bash: |
          mkdir -p $(System.DefaultWorkingDirectory)/arm_ttk_test_results
        displayName: Preapare  ARM-TTk tests env

      - bash: |
          PATH=/home/vsts/bin:$PATH && \
          PATH=$HOME/bin:$PATH && \
          PATH=/home/vsts/.local/bin:$PATH && \
          cd $(System.DefaultWorkingDirectory)/modules/bats && bash run_all_tests.sh
        displayName: Run tests

      - task: PublishTestResults@2
        displayName: Publish Framework BATS Tests Results
        inputs:
          failTaskOnFailedTests: true
          testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
          testResultsFiles: '**/TestReport-*.xml'

      - task: RunARMTTKTests@1
        inputs:
          templatelocation: '$(System.DefaultWorkingDirectory)/pipelines/azure/arm/k8.json'
          resultLocation: '$(System.DefaultWorkingDirectory)/arm_ttk_test_results'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'NUnit'
          testResultsFiles: '$(System.DefaultWorkingDirectory)/kubernetes/tmp/*-armttk.xml'
        condition: always(