parameters:
  - name: mode
    displayName: 'Which template to use ?'
    type: string
    default: jmeter

jobs:
  - ${{ if not(eq(parameters.mode, 'tests')) }}:
      - template: run.jmeter.kubernetes.template.yaml
  - ${{ if eq(parameters.mode, 'tests') }}:
      - template: run.jmeter.kubernetes.template.tests.yaml