jobs:
  - job: bats_tests
    displayName: BASH modules tests
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 5
    steps:
      - checkout: crux
        displayName: CRUX clone

      - task: ShellScript@2
        displayName: Install BATS
        inputs:
          scriptPath: $(System.DefaultWorkingDirectory)/modules/bats/install.sh

      - bash: |
          PATH=/home/vsts/bin:$PATH && \
          PATH=$HOME/bin:$PATH && \
          PATH=/home/vsts/.local/bin:$PATH && \
          cd $(System.DefaultWorkingDirectory)/modules/bats && bash run_all_tests.sh
        displayName: Run tests

      - task: PublishTestResults@2
        displayName: Publish Framework BATS Tests Results
        inputs:
          failTaskOnFailedTests: true
          testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
          testResultsFiles: '**/TestReport-*.xml'

  - job: arm_and_pester_tests
    displayName: Powershell modules and ARM tests
    timeoutInMinutes: 5
    pool:
      vmImage: 'windows-latest'
    steps:
      - checkout: crux
        displayName: CRUX clone

      - powershell: |
            New-Item -ItemType Directory -Force -Path $(System.DefaultWorkingDirectory)\arm_ttk_test_results
            New-Item -ItemType Directory -Force -Path $(System.DefaultWorkingDirectory)\modules\pester\results
        displayName: Prepare

      - task: PowerShell@2
        displayName: Run Pester tests with Coverage
        inputs:
          arguments: 'azure'
          filePath: '$(System.DefaultWorkingDirectory)\modules\pester\RunAllTests.ps1'
          pwsh: true

      - task: PublishTestResults@2
        displayName: Publish Pester tests
        inputs:
          testResultsFormat: 'NUnit'
          testResultsFiles: '$(System.DefaultWorkingDirectory)/modules/pester/results/*pesterTEST.xml'
          failTaskOnFailedTests: true

      - script: 'dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.5.8'
        displayName: 'Install ReportGenerator tool'

      - script: 'reportgenerator -reports:"$(System.DefaultWorkingDirectory)/modules/pester/results/*pesterCoverageTEST.xml" -targetdir:"$(System.DefaultWorkingDirectory)/modules/pester/results/" -reporttypes:HtmlInline_AzurePipelines'
        displayName: 'Create reports'

      - task: PublishCodeCoverageResults@1
        displayName: Publish Pester Code Coverage
        inputs:
          codeCoverageTool: 'JaCoCo'
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/modules/pester/results/*pesterCoverageTEST.xml'
          reportDirectory: "$(System.DefaultWorkingDirectory)/modules/pester/results/"

      - task: RunARMTTKTests@1
        displayName: Run ARM TTK tests
        inputs:
          templatelocation: '$(System.DefaultWorkingDirectory)\pipelines\azure\arm\k8.json'
          resultLocation: '$(System.DefaultWorkingDirectory)\arm_ttk_test_results'

      - task: PublishTestResults@2
        displayName: Publish ARM TTK tests
        inputs:
          testResultsFormat: 'NUnit'
          testResultsFiles: '$(System.DefaultWorkingDirectory)\arm_ttk_test_results\*-armttk.xml'

  - job: docker_images_tests
    displayName: Docker images tests
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 5
    strategy:
      matrix:
        master:
          containerImage: 'gabrielstar/crux-master'
        slave:
          containerImage: 'gabrielstar/crux-slave'

    steps:
      - bash: |
          groovy -v
        displayName: Check groovy version
