jobs:
  - job: Debug
    displayName: Mode selection
    steps:
      - bash: |
            echo "Run mode selected:"  $(mode)
            echo "Parameter:"  ${{ parameters.mode }}
        displayName: Display selected mode

    - template: run.jmeter.kubernetes.template$(mode).yaml