parameters:
  - name: mode
    displayName: 'Which template to use ?'
    type: string
    default: jmeter

jobs:
  - job: JMeter_Tests
    variables:
      - template: default.variables.yaml
        parameters:
          mode: ${{ parameters.mode }}

    displayName: JMeter Tests
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 5
    steps:
    - checkout: crux
      displayName: CRUX clone
      condition: and(succeeded(), not(eq(variables.crux_clone, false)))

    - checkout: tests
      displayName: TESTS clone
      condition: and(succeeded(), not(eq(variables.tests_clone, false)))

    - bash: |
        mkdir -p $(reposRoot) && cp -r $(repoName) $(System.DefaultWorkingDirectory)/$(reposRoot)/$(repoName)
        cp -r $(cruxRepoName)/* $(System.DefaultWorkingDirectory)/
      displayName: PREPARE tests
      condition: and(succeeded(), not(eq(variables.prepare_tests, false)))

    - task: KubernetesManifest@0
      displayName: Scale slaves to $(scale_down_replicas)
      condition: and(succeeded(), not(eq(variables.scale_slaves_down, false)))
      inputs:
        kubernetesServiceConnection: $(kubernetesServiceConnection)
        action: scale
        kind: deployment
        name: $(service)
        replicas: $(scale_down_replicas)
        namespace: $(cluster_namespace)

    - task: KubernetesManifest@0
      displayName: Scale master to $(scale_down_replicas)
      condition: and(succeeded(), not(eq(variables.scale_master_down, false)))
      inputs:
        kubernetesServiceConnection: $(kubernetesServiceConnection)
        action: scale
        kind: deployment
        name: $(service-master)
        replicas: $(scale_down_replicas)
        namespace: $(cluster_namespace)

    - task: KubernetesManifest@0
      displayName: Scale master to $(scale_up_replicas_master)
      condition: and(succeeded(), not(eq(variables.scale_master_up, false)))
      inputs:
        kubernetesServiceConnection: $(kubernetesServiceConnection)
        action: scale
        kind: deployment
        name: $(service-master)
        replicas: $(scale_up_replicas_master)
        namespace: $(cluster_namespace)

    - task: KubernetesManifest@0
      displayName: Scale slaves to $(scale_up_replicas)
      condition: and(succeeded(), not(eq(variables.scale_slaves_down, false)))
      inputs:
        kubernetesServiceConnection: $(kubernetesServiceConnection)
        action: scale
        kind: deployment
        name: $(service)
        replicas: $(scale_up_replicas)
        namespace: $(cluster_namespace)

    - task: Kubernetes@1
      displayName: Login to cluster
      condition: and(succeeded(), not(eq(variables.login_to_cluster, false)))
      inputs:
        command: login
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(kubernetesServiceConnection)

    - task: ShellScript@2
      displayName: JMeter tests
      condition: and(succeeded(), not(eq(variables.jmeter_tests, false)))
      inputs:
        scriptPath: kubernetes/bin/start_test_from_script_params.sh
        args: $(cluster_namespace) $(reposRoot)/$(scenario) $(data_file) "$(jmeter_args)"

    - task: PublishPipelineArtifact@1
      displayName: Archive JMeter Report
      condition: not(eq(variables.archive_jmeter_report, false))
      inputs:
        path: $(report_dir)
        artifact: JmeterReport

    - task: PublishPipelineArtifact@1
      condition: not(eq(variables.archive_results_file, false))
      displayName: Archive Results file
      inputs:
        path: $(results)
        artifact: results.csv

    - task: PublishPipelineArtifact@1
      condition: not(eq(variables.archive_log, false))
      displayName: Archive Log
      inputs:
        path: $(log)
        artifact: jmeter.log

    - task: ShellScript@2
      displayName: Evaluate as JUNIT tests
      condition: not(eq(variables.evaluate_as_junit_tests, false))
      inputs:
        scriptPath: modules/junit/evaluateTestResultsAsJunit.sh
        args: $(System.DefaultWorkingDirectory)/$(report_dir)/statistics.json $(System.DefaultWorkingDirectory)/modules/junit/results $(System.DefaultWorkingDirectory)/modules/junit/templates $(reposRoot)/$(thresholds_file)

    - task: PublishTestResults@2
      displayName: Publish JUNIT results
      condition: not(eq(variables.publish_junit_results, false))
      inputs:
        testResultsFiles: '**/*_TEST.xml'
        failTaskOnFailedTests: true