# This pipeline requires azure service connection of type "kubernetes service"
# Remember to have 1-1 jmeter service to k8 node (VM)/pod ratio - otherwsie some slaves can crash due to lack of resources

name: $(BuildID)
trigger: none
#config
variables:
  kubernetesServiceConnection: k8con3
  service: jmeter-slaves
  service-master: jmeter-master
  namespace: default

jobs:
  - job: JMeter_Tests
    displayName: Attach to existing cluster
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 5
    steps:

    - task: Kubernetes@1
      displayName: Login to cluster
      inputs:
        command: login
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(kubernetesServiceConnection)

    - bash: |
        kubectl delete -n $(namespace) pods,services -l jmeter_mode=slave ||:
        kubectl delete -n $(namespace) pods,services -l jmeter_mode=master ||:
        kubectl delete -n $(namespace) deployment.apps -l jmeter-slaves

        kubectl create  -n $(namespace) -f kubernetes/config/deployments/jmeter_slaves_deploy_v16.yaml
        kubectl create  -n $(namespace) -f kubernetes/config/deployments/jmeter_slaves_svc.yaml
        kubectl create  -n $(namespace) -f kubernetes/config/deployments/jmeter_master_configmap.yaml
        kubectl create  -n $(namespace) -f kubernetes/config/deployments/jmeter_master_deploy_v16.yaml
      displayName: Re-deploy services to cluster