# This pipeline requires azure service connection of type "kubernetes service"
# Remember to have 1-1 jmeter service to k8 node (VM)/pod ratio - otherwsie some slaves can crash due to lack of resources

name: $(BuildID)
trigger: none
parameters:
- name: mode
  default: jmeter
  values:
    - tests
    - jmeter
- name: data_file
  default: test_data/sample_data.csv
- name: jmeter_slaves
  default: 3
  type: number
- name: repo_name
  default: jmeter_simple_test
  type: string

variables:
  cluster_namespace: default
  kubernetesServiceConnection: k8con2
  scale_down_replicas: 0
  scale_up_replicas: ${{ parameters.jmeter_slaves }}
  scale_up_replicas_master: 1
  service: jmeter-slaves
  service-master: jmeter-master
  data_file: "test_data/sample_data.csv"
  threads: 1 #browsers per pod (=node=VM)
  loops: 1
  jmeter_args: "-Gthreads=$(threads) -Gloops=$(loops)"
  repoName: ${{ parameters.repo_name }}
  user: user
  pass: pass
  repoBaseURL: https://$(user):$(pass)@github.com/ObjectivityLtd
  repoURL: $(repoBaseURL)/$(repoName)
  scenario: $(repoName)/path/to/jmeter/script/test.jmx

jobs:
  - template: templates/run.mode.selector.yaml
    parameters:
      mode: ${{ parameters.mode }}